### ISSUE TITLE
Confusing information on the configuration of the firewall

### ISSUE THREAD

**Issue by Franky1** [jitsi/handbook#11]
Page **DevOps Guide (dedicated server)**
Chapter **Setup and configure your firewall**

Confusing information on the configuration of the firewall:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#setup-and-configure-your-firewall
Source:
https://github.com/jitsi/handbook/blob/master/docs/devops-guide/quickstart.md

In the text **port 4443** is _not_ mentioned, in the UFW configuration below port **4443/tcp** suddenly appears.
Is port 4443 needed or not?
What is the function of port 4443?
Please compare text and ufw configuration and adjust it.

**Comment by luixxiul** [comment]
@MagicFab do you have any idea on this?

**Comment by saghul** [comment]
4443 is the default fallback port for audio / video media over TCP.

**Comment by MagicFab** [comment]
Yes, I'd say needed, it looks like it was fixed.
