### ISSUE TITLE
Confusing instructions for /etc/hosts

### ISSUE THREAD

**Issue by akemper** [jitsi/handbook#118]
Hi,

the comment "..., associating it with the loopback address" in [Debian/Ubuntu server](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart#set-up-the-fully-qualified-domain-name-fqdn-optional) guide is a bit confusing. Why should the entry to resolve the FQDN to the public IP specifically be written next to the default localhost line? I don't see any obvious need for this "association" and would rather add this to the end of the file. Furthermore, is this local FQDN to public IP resolution really optional, i.e. would Jitsi also work without this and / or setting the correct name in /etc/hostname?

Thx
Andreas

**Comment by toby63** [comment]
@saghul

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/handbook/commit/9f84b92df45144a9a9e9d6a60ba5a2a3e22ba9b4

**Comment by toby63** [comment]
Remaining question:
> Furthermore, is this local FQDN to public IP resolution really optional, i.e. would Jitsi also work without this and / or setting the correct name in /etc/hostname?

Quote from the website:
> Set up the Fully Qualified Domain Name (FQDN) (optional)
