### ISSUE TITLE
Broken link at Jitsi FAQ to installation

### ISSUE THREAD

**Issue by gene1wood** [jitsi/handbook#122]
On the Jitsi FAQ at https://jitsi.org/user-faq/ in the `How do I setup my own Jitsi installation?` section where it says `For other systems, or if you wish to install all components manually, see the detailed manual installation instructions.` it links to this URL

https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md

which 404's

I suspect the link should be updated to this URL

https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-manual

**Comment by toby63** [comment]
@saghul 

In addition it could also link to the quickstart guide directly: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart

**Comment by saghul** [comment]
Thanks, I'll fix those.

**Comment by RayBB** [comment]
@saghul are you still planning to fix this?

**Comment by saghul** [comment]
Fixed it!
