### ISSUE TITLE
Create users in Prosody (internal auth) is wrong

### ISSUE THREAD

**Issue by Brotpilot-921** [jitsi/handbook#143]
The Comand "sudo prosodyctl register <username> jitsi-meet.example.com <password>" does not work.
On my Ubuntu Machine I had to use "prosodyctl adduser username@jitsi-meet.example.com" and then enter a new Password. 
I installed Jisti after your dokumenation.

**Comment by saghul** [comment]
It works just fine here. What prosody version are you using?
