### ISSUE TITLE
Guide users to https://jitsi.org/security/

### ISSUE THREAD

**Issue by luixxiul** [jitsi/handbook#15]
Guide users to https://jitsi.org/security/

Because https://jitsi.org/security/ should be the only source of the information (to avoid inconsistency), the URL only should be added to `faq.md` with questions, and other related documents if any. cf: https://jitsi.github.io/handbook/docs/security

Hinted by https://github.com/jitsi/jitsi-meet/issues/6791#issuecomment-631255809.

**Comment by saghul** [comment]
👍

**Comment by saghul** [comment]
Is there anything actionable here @luixxiul ?I think we already added some links.

**Comment by luixxiul** [comment]
Yeah right, maybe I have missed something there 😓 Closing.
