### ISSUE TITLE
FAQ - What does the JITSI acronym stand for?

### ISSUE THREAD

**Issue by SvenAERTS228** [jitsi/handbook#180]
Hi, coming in from cognitive sciences.
People's brains need "mental, instructional scaffolding" help to remember this new and bizarre acronym, word "JITSI".
E.g.: JITSI video collaboration application
and inspired by [[(https://en.wikipedia.org/wiki/Jitsi#Jitsi_Desktop)]]
I got: 
J = JavaScript application,
I = Interface
T = Talk & Video & Conference & Stream & More
S = Secure 
I = Instant Encrypted

:) Cheers

**Comment by damencho** [comment]
https://desktop.jitsi.org/Documentation/FAQ.html#spelling
