### ISSUE TITLE
Include prosody .11 in Self-Hosting Guide - Debian/Ubuntu server

### ISSUE THREAD

**Issue by myfirstnameispaul** [jitsi/handbook#216]
Ubuntu 18.04 has Prosody .10 in the repos.

[This forum post](https://community.jitsi.org/t/how-to-how-do-i-update-prosody/72205) explains how to update to .11, which is required for certain features, including the lobby feature.

I haven't tested below on installing from fresh OS, but I think the following should work for new installs:

At [line 79](https://github.com/jitsi/handbook/blob/master/docs/devops-guide/quickstart.md), insert:

````text
### For Ubuntu 18.04, add Prosody package repository

This will add the Prosody repository so that Prosody .11 will be installed, which is necessary for features including the lobby feature.

```sh
echo deb http://packages.prosody.im/debian $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list
wget https://prosody.im/files/prosody-debian-packages.key -O- | sudo apt-key add -
```

````

**Comment by saghul** [comment]
Can you please make an actual pull request with that change?

**Comment by saghul** [comment]
In general, we can probably recommend the Prosody repo, so users are more up to date.
