### ISSUE TITLE
Transfer documentation from Jitsi projects

### ISSUE THREAD

**Issue by luixxiul** [jitsi/handbook#22]
Now that files under `doc/` on `jitsi-meet` have been transferred to this handbook, I think documentation of the other projects should also be transferred.

Here are the projects on which are worked actively:

- [x] [`docker-jitsi-meet`](https://github.com/jitsi/docker-jitsi-meet)
- [x] [`jitsi-meet`](https://github.com/jitsi/jitsi-meet/tree/master/doc)
- [ ] [`jicofo`](https://github.com/jitsi/jicofo/tree/master/doc)
- [ ] [`jitsi-videobridge`](https://github.com/jitsi/jitsi-videobridge/tree/master/doc)
- [ ] [`jigasi`](https://github.com/jitsi/jigasi) (README.md)
- [ ] [`jitsi-meet-electron`](https://github.com/jitsi/jitsi-meet-electron) (README.md)
- [ ] [`lib-jitsi-meet`](https://github.com/jitsi/lib-jitsi-meet/tree/master/doc)
- [ ] [`jibri`](https://github.com/jitsi/jibri/tree/master/doc)

Some of them would be under `dev-guide/`, the others under `devops-guide/`. For example, documentation of `lib-jitsi-meet` would be transferred under `dev-guide/`.

**Comment by yashodhanmohan** [comment]
Hope this PR - #83 -  helps in moving this forward. It's not the complete thing but it is step 1.
It moves over lib-jitsi-meet's documentation into handbook.
