### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by Commifreak** [jitsi/handbook#224]
Would be great if you could cover LDAP from here: https://github.com/jitsi/jitsi-meet/wiki/LDAP-Authentication - but with official ways how to do it (if there is something missing).

**Comment by ulab** [comment]
Since I started the LDAP Wiki page I'd love to contribute, but I am not sure which of the two ways (via ldap2 or saslauthd) is the preferred one.

**Comment by saghul** [comment]
Thanks for volunteering! I think we have saslauthd support in the Docker setup, so I'd say that's a good start.

**Comment by Commifreak** [comment]
> Thanks for volunteering! I think we have saslauthd support in the Docker setup

Correct
