### ISSUE TITLE
Clarify that building the applications is not supported on Windows in Developer Guide (Web)

### ISSUE THREAD

**Issue by shane215** [jitsi/handbook#237]
The Developer Guide (Mobile) clarifies that _building the applications is not supported on Windows_ but this is not mentioned in the Developer Guide (Web).

This confused me as I'm only looking at the Web guide.

Others in the community seem confused too, e.g. [Deploying and installing Jitsi-meet on WINDOWS xampp/htdocs](https://community.jitsi.org/t/deploying-and-installing-jitsi-meet-on-windows-xampp-htdocs/65324).

I propose to put the same note under _Building the sources_ on the _Start_ page of Developer Guide (Web).

**Comment by shane215** [comment]
I'm happy to work on this issue, but I don't have permission to assign it.

**Comment by saghul** [comment]
You don't need to assign anything :-) Just create a PR and we'll take it from there, thanks a lot!
