### ISSUE TITLE
[Request] Rename the DevOps-Guide

### ISSUE THREAD

**Issue by toby63** [jitsi/handbook#26]
At least I was confused what "DevOps" should be about and where I find the information about setting up a server.
To avoid confusion, I recommend changing the Name to either:
* Server-Guide
* Administration-Guide (or Admin-Guide)

or similar.

**Comment by luixxiul** [comment]
Is this request / suggestion?

**Comment by toby63** [comment]
> Is this request / suggestion?

Well...it says exactly that in the title :point_up:, so yes.

**Comment by saghul** [comment]
Agreed. I think "Self-Hosting guide" is the clearest.

**Comment by luixxiul** [comment]
Which one? 😂 

- `Self-Hosting guide`
- `self-hosting guide`
- `Self-hosting Guide`
- `Self-Hosting Guide`

**Comment by toby63** [comment]
probably three:
`Self-hosting Guide`

**Comment by saghul** [comment]
Done :-)

**Comment by toby63** [comment]
Not really:
* https://github.com/jitsi/handbook/blob/master/website/sidebars.json
* https://github.com/jitsi/handbook/blob/master/docs/intro.md

I don't have time for pull requests right now; I just wanted to mention it, before its forgotten.

By the way you might consider renaming things (like files etc.), so the names fight together and the code will be better readable (also in the future).

**Comment by saghul** [comment]
Fixed.

> By the way you might consider renaming things (like files etc.), so the names fight together and the code will be better readable (also in the future).

Files sure, but the document ids are used to generate the links, and I'd rather not change those.
