### ISSUE TITLE
Update breakout rooms documentation

### ISSUE THREAD

**Issue by erotavlasme** [jitsi/handbook#263]
Hi,
since that now jitsi has a native [breakout rooms](https://github.com/jitsi/jitsi-meet/issues/5550) support. The corresponding [handbook page](https://jitsi.github.io/handbook/docs/community/breakout-rooms) should be updated.
Thank you

**Comment by Freddie-m** [comment]
It's not in stable yet. I think a few kinks are still being worked out, so perhaps the update should come after it's been pushed to stable.

**Comment by saghul** [comment]
Correct, I'll update the handbook once the feature has shipped.

**Comment by saghul** [comment]
https://github.com/jitsi/handbook/commit/48c7a8041a62bddf8c449a9e1c715aea73568327
