### ISSUE TITLE
[Request] Changes to Dedicated Server Guide 

### ISSUE THREAD

**Issue by toby63** [jitsi/handbook#27]
Right now it is a bit confusing, so I would suggest some changes:
1. Rename "Dedicated Server"-Page to `Installation on Debian/Ubuntu` or something similar, so people can directly see what this page will be about.
2. You could add a general introduction for "Installation" or "Deployment" that clarifies the different methods (Debian, Docker, Manual) and when to use them.

**Comment by saghul** [comment]
Both sound good to me, would you like to send a PR?

**Comment by toby63** [comment]
I will see how much time I have to contribute, but I will consider sending pull requests for some things :slightly_smiling_face: .
