### ISSUE TITLE
Incomplete Doc on Handbook

### ISSUE THREAD

**Issue by complabs28** [jitsi/handbook#279]
I found an incomplete doc on `https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile-jitsi-meet#android` and I have to build the app for android. I can't figure out how to build it. Please Complete the doc on `https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-mobile-jitsi-meet#android`

**Comment by saghul** [comment]
What are you missing? Where did you get stuck?

**Comment by saghul** [comment]
We don't support building on Windows. This is written in red letters at the top of that page.
