### ISSUE TITLE
Bad Link in Handbook

### ISSUE THREAD

**Issue by ilcylic** [jitsi/handbook#284]
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-manual#install-jitsi-videobridge

"Visit https://download.jitsi.org/jitsi-videobridge/linux to determine the current build number, download and unzip it:"

Link is 404, correct link appears to be https://jitsi.org/downloads/

**Comment by saghul** [comment]
Thanks for catching that! Mind sending a PR?

**Comment by ilcylic** [comment]
Well, no, I take that last part back.  That link does not seem to lead to the .zip files mentioned in the handbook.

Has the manual Installation been completely deprecated by removing the file availability?

Please advise.

**Comment by ilcylic** [comment]
Re: Pull request -- No, I'm sorry, I don't really know what that means (other than "some github thing") and don't have time to figure it out.

**Comment by saghul** [comment]
Makes sense, thanks!

**Comment by ShwetKhatri2001** [comment]
I'd like to fix this issue and start contributing to Jitsi.
