### ISSUE TITLE
Link on Website broken

### ISSUE THREAD

**Issue by muellert** [jitsi/handbook#292]
If I am on this website:

https://jitsi.org/downloads/

there is a link in the text that reads "If you want to self-host your own Jitsi Meet instance you can follow the installation instructions in [our handbook](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-start). If you want to download the individual packages by hand, please see below."

If I click that link, I get a 404 error.

**Comment by saghul** [comment]
Hum, looks like the update to Docusaurus v2 messed up the "start" links, aka the first ones of the section. I'll take a look, thanks for the report.

**Comment by saghul** [comment]
Fixed.
