### ISSUE TITLE
help: Broken link to docs/intro

### ISSUE THREAD

**Issue by nomadbyte** [jitsi/handbook#351]
The [help page](https://jitsi.github.io/handbook/help/) (which opens from Jitsi-Meet Help)  contains a broken link to docs/intro: [handbook/help/docs/intro](https://jitsi.github.io/handbook/help/docs/intro) ==> 'Page Not Found'.

The correct path seems to be [handbook/docs/intro](https://jitsi.github.io/handbook/docs/intro).

**Comment by saghul** [comment]
Oh, thanks for the heads up!
