### ISSUE TITLE
Complete docs/user-guide/use-jitsi-meet-on-mobile.md

### ISSUE THREAD

**Issue by luixxiul** [jitsi/handbook#36]
Via: #28

**Comment by toby63** [comment]
FYI:
@hpdang is already working on this: https://github.com/jitsi/handbook/pull/42/

**Comment by toby63** [comment]
We should maybe discuss what exactly should be included in such a guide and what the structure should be.

Some open questions:
* Should iOS and Android be seperated?
    * Related question is: Are the Apps (very) different or not (both in terms of functionality and look)? If yes we should seperate them.
* Should we describe how to **join** and **start** a jitsi-meeting in this guide as well?
  I think this might be the best way, to avoid confusion that comes with different UIs.
