### ISSUE TITLE
Typo in docs/devops-guide/docker.md : JVB_ADVERSITED_IPS

### ISSUE THREAD

**Issue by gitouche-sur-osm** [jitsi/handbook#378]
Hello, you have a typo in the docs : 
JVB_ADVERSITED_IPS is used but the correct name seems to be JVB_ADVERTISE_IPS

Introduced : https://github.com/jitsi/handbook/commit/bf68bac5c0b887393c8bdf01d00a7d42e1956d1e#diff-2076c592029895cb20061ec54b123d045d2f92911c67939563f9ff88370f7e21R681

**Comment by saghul** [comment]
Thanks! Mind sending a PR?
