### ISSUE TITLE
Marketing suggestion: highlight key Jitsi features and benefits on handbook homepage (?)

### ISSUE THREAD

**Issue by jayaddison** [jitsi/handbook#40]
There are frequent conversations at the moment about how to determine what videoconferencing solution to use, in various social and work environments.

* People aren't sure what operating systems / browsers different conferencing services work on (or sometimes what the names of those environments and platforms are)
* System and business decision-makers may have little time to assess each service they're evaluating -- and are more likely to have heard of market-leading products, due to their relative ability to perform passive and inbound marketing
* People aren't sure about the security and privacy properties of the services available

Would the homepage of the Jitsi handbook be a good place to locate some 'marketing-like' summary information to aid decision-making?

Since it's on my mind currently, I'd like to leave some notes on a suggested approach, involving a single sentence for each talking point -- concise, correct and true -- for a number of potentially-relevant items:

- Completely free videoconferencing for groups
- Supported by all major web browsers
- Single-click-to-join meetings using standard web hyperlinks
- No user accounts required
- Creation and entry to meetings can be restricted
- Cloud-hosted or on-premise deployment options
- Built upon widely-deployed and well-tested secure videoconferencing technology
- Is open source and incorporates software, documentation and translation improvements from a large community

**Comment by saghul** [comment]
Thanks for the suggestions, makes sense!

**Comment by eknoes** [comment]
I felt quite lost on the Handbooks startpage and think this might be a good solution. Furthermore, referring to download links for Jitsi Meet and a "Get Started" button or similar which is just a link to the docs article would be nice, so that you are pushed to continue staying and reading about Jitsi.

**Comment by saghul** [comment]
Thanks for the feedback. Note that this effort just started, so it will take us a while to get where we need to be.

**Comment by toby63** [comment]
I think the startpage (https://jitsi.github.io/handbook/) should be https://jitsi.github.io/handbook/docs/intro

Also I disagree with the suggestions of this issue, a handbook page is imo not the right place to promote the features etc.
This can be put on the [main website](https://jitsi.org/jitsi-meet/) and in the [Github Readme](https://github.com/jitsi/jitsi-meet/blob/master/README.md).

**Comment by jayaddison** [comment]
Those seem reasonable to me, @toby63 - I admit I hadn't seen the [Jitsi-Meet homepage](https://jitsi.org/jitsi-meet/) you linked to (which is nice and clear), and instead had only seen the top-level [Jitsi](https://jitsi.org/) homepage, which in my opinion is a bit noisier and less clear for decision-making purposes.

Once we gain a bit more consensus about whether these items belong in the handbook I'm happy to draft up some markup for them or close this issue, whichever is more appropriate.

**Comment by saghul** [comment]
You don't know how a user will end up in what page.

**Comment by toby63** [comment]
> You don't know how a user will end up in what page.

We can add a link to the main website of jitsi-meet as an alternative.

**Comment by jayaddison** [comment]
I think this can be closed and archived under "curiosities from the COVID-19 pandemic era".  Jitsi seems to have done well at attracting an audience over the past year or so :)
