### ISSUE TITLE
Home page is not responsive

### ISSUE THREAD

**Issue by Dev-Code24** [jitsi/handbook#406]
The docs website's home page is not responsive at all and the issue is with the iframe div in index.js file
Following are the videos to show the issue here

https://user-images.githubusercontent.com/97425135/209653374-a7957878-4b65-47f4-b3c8-7c5e70c85937.mov

https://user-images.githubusercontent.com/97425135/209653360-65c3a593-0a7c-4097-bb63-13f9d55e44b4.mov

**Comment by Dev-Code24** [comment]
Can anyone committed to the repository assign this to me?

**Comment by saghul** [comment]
There is no need to assign it, if you can fix it please make a PR and we'll review it. Thank you!

**Comment by Dev-Code24** [comment]
> There is no need to assign it, if you can fix it please make a PR and we'll review it. Thank you!

I have fixed the issue but after solving the issue I saw that the footer needs a bit of work to look better. So I want to work on that too but I was unable to find the folder/file of the footer. So can you please help me with that?

**Comment by saghul** [comment]
Thank you!

IIRC the footer is automatic, from the Docusaurus theme. Maybe that got fixed in a later version?

**Comment by saghul** [comment]
![image](https://user-images.githubusercontent.com/317464/209788643-04b24d91-c2be-4485-b2f8-609a845ab4c5.png)

The footer looks good here though!

**Comment by Dev-Code24** [comment]
> ![image](https://user-images.githubusercontent.com/317464/209788643-04b24d91-c2be-4485-b2f8-609a845ab4c5.png)
> 
> The footer looks good here though!

Yes it looks good, I just wanted to make it look a bit more eye-pleasing

**Comment by saghul** [comment]
It's automatically generated, so I'm not sure how customizable it is

**Comment by Dev-Code24** [comment]
> It's automatically generated, so I'm not sure how customizable it is 

Ok got it.
