### ISSUE TITLE
[Request] Describe privacy friendly solution for video recording

### ISSUE THREAD

**Issue by toby63** [jitsi/handbook#46]
The FAQ (https://jitsi.github.io/handbook/docs/faq#can-i-record-and-save-the-video) mentions only youtube and dropbox as solutions to record their conference.

There should be a different solution that is more privacy friendly and independend from the Big Companies.

**Comment by aaronkvanmeerten** [comment]
We are happy to take PRs for the required components to support other methods.  What did you have in mind?

By the way, this isn't just a documentation issue however, any new upload or streaming methods requires cod echanges in each component of the services to support these new methods.  So likely this isn't the only (or necessarily correct) place to track this request.

**Comment by toby63** [comment]
> What did you have in mind?

A solution on the users computer would be best.
Maybe a recording function in the browser, or a possibility to access the stream via VLC or other media players, so they can record it.

> By the way, this isn't just a documentation issue however, any new upload or streaming methods requires cod echanges in each component of the services to support these new methods. So likely this isn't the only (or necessarily correct) place to track this request.

I agree, I just noticed this point in the FAQ (because I was looking at recent PullRequests) so I opened this issue here first, because I also don't know what features regarding this issue are already implemented in both jitsi and browsers.

**Comment by toby63** [comment]
Related to https://github.com/jitsi/jitsi-meet/issues/6014

**Comment by gabrc52** [comment]
In the meantime, if you want a local recording, you could use OBS to record the meeting on your own computer.

**Comment by toby63** [comment]
@gabrc52 So OBS can record specific browser windows?

**Comment by gabrc52** [comment]
Yes, OBS can record any window, in the case of Jitsi Meet, a browser window with the meeting, or the desktop client (jitsi-meet-electron).

I've tested it on Linux and a Chromium based browser and it works pretty fine.

I've tested it on Windows and Microsoft Teams and it works sort of fine (it doesn't let you hide the cursor).

**Comment by toby63** [comment]
Thank you :slightly_smiling_face:. That sounds very useful. I will add it to the handbook.

**Comment by gabrc52** [comment]
Another (more complicated, but OK if you have the infrastructure) alternative: since you can now livestream to any RTMP endpoint, you could make your own private RTMP server and stream to that (instead of a YouTube stream key add the whole rtmp url including the domain and stream key). You wouldn't need your own Jitsi or Jibri instance, but an RTMP server

**Comment by toby63** [comment]
Good to know that the rtmp method is now possible.

The Jitsi team should really work on their Public Relations, information should be centralised to see what there is todo and what is already implemented.

I will add a note of this as well.

**Comment by toby63** [comment]
With https://github.com/jitsi/handbook/pull/108 being merged, I will close this issue for now, as some privacy friendly methods are now mentioned.
