### ISSUE TITLE
Misleading description for userInfo API object?

### ISSUE THREAD

**Issue by JonasDoe** [jitsi/handbook#462]
At two places, in [docs/dev-guide/iframe.md](https://github.com/jitsi/handbook/blob/9b329fa4e849affa173b07c1a4302cd11b0add1d/docs/dev-guide/iframe.md?plain=1#L100) and in [docs/dev-guide/react-sdk.md](https://github.com/jitsi/handbook/blob/9b329fa4e849affa173b07c1a4302cd11b0add1d/docs/dev-guide/react-sdk.md?plain=1#L101), the documentation about the `userInfo` parameter states that these are information `"about the participant starting the meeting"`. I figure, it's the information for _any_ participant, not only the one starting the meeting? Or is there another place to set the currrent participant's user name?

**Comment by saghul** [comment]
That's right it's the information about the current participant, regardless of who started the meeting.

**Comment by JonasDoe** [comment]
Thanks for the response - shall I create a PR with the adjustment or isn't it worth it?

**Comment by saghul** [comment]
That would be very helpful yeah!
