### ISSUE TITLE
User guide doesn't mention moderators requirements

### ISSUE THREAD

**Issue by ledenis** [jitsi/handbook#496]
The [Start a Jitsi Meeting](https://jitsi.github.io/handbook/docs/user-guide/user-guide-start-a-jitsi-meeting) or [Join a Jitsi Meeting](https://jitsi.github.io/handbook/docs/user-guide/user-guide-join-jitsi-meeting) pages suggest that users can join a meeting on meet.jit.si without a moderator / logged-in user, which is no longer true.

Maybe add this information into these pages?

**Comment by saghul** [comment]
I made a couple of clarifying commits, thanks for the heads up!

**Comment by ledenis** [comment]
Wow that was quick, thank you!
