### ISSUE TITLE
UDP port 4446

### ISSUE THREAD

**Issue by simolev** [jitsi/handbook#50]
I just followed the [tutorial](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart) on a fresh Ubuntu 20.04. Found issues using the Android app that were resolved when I opened UDP port 4446, not mentioned in the tutorial.

The issues were only when connecting via the mobile network, Wi-Fi seemed fine.  
UDP port 4446 is mentioned in `/etc/turnserver.conf` as `listening-port=4446`.

**Comment by toby63** [comment]
@saghul Could you (or someone else from the team) comment on this?
Would be valuable to add it to the Handbook, if the information correct.

**Comment by saghul** [comment]
I believe we have reverted that behavior in the latest stable update because it caused problems. You can revert to the previous non-multiplexing behavior by following: https://jitsi.github.io/handbook/docs/devops-guide/faq
