### ISSUE TITLE
Speaker Queue

### ISSUE THREAD

**Issue by W3sley0Bi** [jitsi/handbook#501]
# Speaker Queue

## Overview

Develop a user interface component that organizes the set of participants that are ready to speak into a queue.

## Description

The [Jitsi Meet](https://github.com/jitsi/jitsi-meet/) system allows participants to raise their hand to indicate that they are ready to speak.
When multiple participants raise their hand, there is no easy way to determine who was first and who should be the next
one to speak.

## Expected outcomes
* User interface components that organize the participants with raised hand into a queue.
* ![SpeakerQueue](https://github.com/jitsi/handbook/assets/42078311/39f4f3b5-98cf-4b0b-ac83-a700f6abe6f5)

## Skills / Technologies

JavaScript, React

## Possible mentors
Saúl Ibarra Corretgé, Calin Chitu, Hristo Terezov

## Expected project size

Small (90 hours)

## Difficulty

Easy/Medium

**Comment by damencho** [comment]
Please do not open issues. Let's stick to the forum. This repository is just documentation and there is no code here.
