### ISSUE TITLE
Jitsi Videobridge Broken Link (File Not Found)

### ISSUE THREAD

**Issue by varghesejose2020** [jitsi/handbook#509]
https://jitsi.github.io/handbook/docs/devops-guide/devops-
![Screenshot_2024_0521_194038](https://github.com/jitsi/handbook/assets/71702982/1efe7301-0503-4190-933b-0a62bb5b8040)
guide-manual#install-jitsi-videobridge

**Comment by damencho** [comment]
Look at the warning on top of that page:

![image](https://github.com/jitsi/handbook/assets/3263098/b5fd9ab5-b0dd-4f2f-aaf7-13b4ef226870)

That page is missing a lot of updates not only that.
