### ISSUE TITLE
Hide hash links in the Jitsi Meet Handbook

### ISSUE THREAD

**Issue by amedinaaa** [jitsi/handbook#517]
### What happened?

Adding in the issue reporting template:

**Provide Detailed Information:** Only pertains to the handbook.

**Description of the Issue:** It looks like several pages of the handbook contain hash links to specific references to subsections within the handbook. The links in themselves are perfectly fine but is it possible we can further hide the "hashes" instead of just setting the opacity to zero? I'm thinking of maybe adding a "display: none" to the "hash-link" class.

Screenshot:  
<img width="1397" alt="Screenshot 2024-07-24 at 7 46 32 PM" src="https://github.com/user-attachments/assets/43f879fd-8fc5-47b8-97ab-490dc5076247">

**Reproduction Steps:** 
1. Go to the handbook: https://jitsi.github.io/handbook/
2. Select any relevant handbook page
3. Hover over a subsection title

**Expected Behavior:** We should ideally completely hide these hash links to readers.

**Actual Behavior:** "Hashes" are apparent when hovering over subsection titles.

### Platform

- [X] Chrome (or Chromium based)
- [X] Firefox
- [X] Safari
- [ ] Other desktop browser
- [ ] Android browser
- [ ] iOS browser
- [ ] Electron app
- [ ] Android mobile app
- [ ] iOS mobile app
- [ ] Custom app using a mobile SDK

### Browser / app / sdk version

Chrome Version: 126.0.6478.127

### Reproducibility

- [ ] The problem is reproducible on meet.jit.si

**Comment by saghul** [comment]
Exactly what @shawnchin says. They are meant to be able to copy the links.
