### ISSUE TITLE
Jitsi Server on Windows

### ISSUE THREAD

**Issue by AltafAllahAbbassi** [jitsi/handbook#64]
Can i install jitsi server in Windows ?If yes How ?

**Comment by toby63** [comment]
This is a topic for the forum: https://community.jitsi.org/
Search the forum first.

Some hints from me.
As far as I know Jitsi (and other connected components) are software for Linux.
So you will need to use a Virtual Machine to use it on windows.
For example: https://www.virtualbox.org/ can create virtual machines.
But this will run slower, so I recommend using Linux directly.

One comment regarding Docker: Docker on Windows also uses a virtual machine, so there is no difference in performance.

While there is now a linux-subsystem in Windows (10), I don't think it is capable for using Jitsi.
But I did not test that.

**Comment by toby63** [comment]
@luixxiul Could you rename this please, into `Jitsi Server on Windows`?

We could add this information to the handbook as well, but someone needs to test it.
I don't use Windows anymore :smile:.

Maybe it could be added to the forum meanwhile.

**Comment by AltafAllahAbbassi** [comment]
Nooo, i didn't . I used VM .

**Comment by saghul** [comment]
Windows is not a supported platform, sorry.
