### ISSUE TITLE
Outdated Quickstart

### ISSUE THREAD

**Issue by MakerStuff** [jitsi/handbook#71]
I was following along the [quickstart guide](https://github.com/jitsi/handbook/blob/master/docs/devops-guide/quickstart.md#generate-a-lets-encrypt-certificate-optional-recommended) until i ran into an error:
```
sudo /usr/share/jitsi-meet/scripts/install-letsencrypt-cert.sh
```
stopped with a python ImportError when creating a new virtual environment
```
[...]
Creating virtual environment...
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 7, in <module>
    from virtualenv import main
ImportError: cannot import name main
Traceback (most recent call last):
  File "<stdin>", line 27, in <module>
  File "<stdin>", line 19, in create_venv
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['virtualenv', '--no-site-packages', '--python', '/usr/bin/python2.7', '/opt/eff.org/certbot/venv']' returned non-zero exit status 1
```

`pip show virtualenv` revealed i am using version 20.0.26 which is the current up-to-date version.

My guess is I either need to downgrade my virtualenv (to which version?) or the code needs some modification.

**Comment by toby63** [comment]
Could you report that here: https://github.com/jitsi/jitsi-meet/issues
As it seems to be a potencial problem with the software and not the handbook.

**Comment by MakerStuff** [comment]
I posted the issue [here](https://github.com/jitsi/jitsi-meet/issues/7341)
