### ISSUE TITLE
Suggestion: When chat is open, allow the main image to fit between the margins

### ISSUE THREAD

**Issue by PhilipOakley** [jitsi/handbook#91]
I used Jitsi on a conference call over the two days recently. Excellent.

One relatively minor issue was that with the chat active, it will hide (the left hand) part of the main screen area, so one can't see part of the presentations, or some of the participants if in gallery view.

It would be nice if their was a 'shrink to fit', or similar, so that the chat can be held open as well as seeing the full conference image, likewise for anything showing on the right hand margin. The chat bar could be detached, to be free-floated, if that was easier.

Thanks.

**Comment by toby63** [comment]
This belongs here:
https://github.com/jitsi/jitsi-meet/issues

**Comment by PhilipOakley** [comment]
Thanks
