### ISSUE TITLE
Avoid using + in version numbers

### ISSUE THREAD

**Issue by bradroid** [jitsi/handbook#97]
In your handbook for Android, you recommend defining the gradle dependency as follows:

`org.jitsi.react:jitsi-meet-sdk:2.+`

Source: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk

This is very dangerous, especially when semantic versioning is not used properly. It means that projects depending on jitsi-meet will automatically update to the latest version, without any changes in the code.

This happened to me, the same code that built just fine few weeks ago is failing to build today.

It's because in your 2.10.0 update, you introduced this change:
`Bump minimum API level to 23 and target API level to 29`

This is a breaking change which breaks all the Android builds which use API lower than 23 as minimum supported API (e.g: I'm using 21). 

I recommend two approaches to avoid this in the future:

1. You should update the major version for breaking changes like this one (this should've been a 3.0.0).
2. Discourage the usage of `2.+` dependency format in your documentation.

**Comment by saghul** [comment]
I don't want to be updating that page with every release we make. That is just an example. If you feel like a warning note should be added please open a PR.
